'use client';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../../lib/api';
import { ApprovalCard, FilterTabs, InsightCards, RecommendationCard, RecordsTable, SelectionActions, StatusChip, TaskRows } from '../../components/BeautifulUI';
import { WorkspaceBoard, useWorkspaceData } from '../../components/WorkspaceWidgets';
import { useRuntimeCopy } from '../../components/useRuntimeCopy';
const states=[['unfamiliar','陌生'],['familiar','有印象'],['explain','能解释'],['example','能举例'],['distinguish','能区分'],['transfer','能迁移'],['evidence_boundary','能判断证据边界'],['stable_expression','能稳定表达']];
export default function LearningPage(){
 const workspace=useWorkspaceData();
 const runtimeCopy=useRuntimeCopy();
 const [topics,setTopics]=useState([]),[topic,setTopic]=useState(''),[concepts,setConcepts]=useState([]),[notes,setNotes]=useState([]),[practice,setPractice]=useState([]),[personas,setPersonas]=useState([]),[bases,setBases]=useState([]),[selectedKb,setSelectedKb]=useState([]),[msg,setMsg]=useState('');
 const [form,setForm]=useState({name:'',definition:''}),[note,setNote]=useState({title:'',body_markdown:'',concept_id:''}),[question,setQuestion]=useState({prompt:'',concept_id:''});
 const [tab,setTab]=useState('concepts'),[attemptDraft,setAttemptDraft]=useState(null);
 async function load(){const [t,k,p]=await Promise.all([api('/topics'),api('/knowledge/bases').catch(()=>({knowledge_bases:[]})),api('/personas')]);setTopics(t.topics||[]);setBases(k.knowledge_bases||[]);setPersonas(p.personas||[]);if(!topic&&t.topics?.length)setTopic(t.topics[0].id)}
 async function loadTopic(id=topic){const [c,n,q]=await Promise.all([api(`/concepts${id?`?topic_id=${id}`:''}`),api(`/notes${id?`?topic_id=${id}`:''}`),api(`/practice${id?`?topic_id=${id}`:''}`)]);setConcepts(c.concepts||[]);setNotes(n.notes||[]);setPractice(q.practice||[])}
 useEffect(()=>{load().catch(e=>setMsg(e.message))},[]);useEffect(()=>{loadTopic(topic).catch(e=>setMsg(e.message));setNote(n=>({...n,concept_id:''}));setQuestion(q=>({...q,concept_id:''}));setAttemptDraft(null)},[topic]);
 async function createConcept(e){e.preventDefault();try{await api('/concepts',{method:'POST',body:JSON.stringify({topic_id:topic||null,name:form.name,definition:form.definition,examples:[],counterexamples:[],confused_with:[],related_claims:[],related_sources:[]})});setForm({name:'',definition:''});await loadTopic();setMsg('概念已建立，当前掌握状态从“陌生”开始。')}catch(e){setMsg(e.message)}}
 async function mastery(id,state){try{await api(`/concepts/${id}/mastery`,{method:'PUT',body:JSON.stringify({state,evidence_note:''})});await loadTopic();}catch(e){setMsg(e.message)}}
 async function assist(id,type){try{const x=await api(`/concepts/${id}/${type}`,{method:'POST',body:JSON.stringify({knowledge_base_ids:selectedKb,focus:''})});setMsg((x.result?.text||JSON.stringify(x.result)).slice(0,700))}catch(e){setMsg(e.message)}}
 async function addNote(e){e.preventDefault();try{await api('/notes',{method:'POST',body:JSON.stringify({topic_id:topic||null,...note})});setNote({title:'',body_markdown:'',concept_id:''});await loadTopic();setMsg(runtimeCopy.noteSavedCopy)}catch(e){setMsg(e.message)}}
 async function addPractice(e){e.preventDefault();try{await api('/practice',{method:'POST',body:JSON.stringify({topic_id:topic||null,...question,question_type:'open'})});setQuestion({prompt:'',concept_id:''});await loadTopic();setMsg('练习已加入。即使答对，也不会自动改变掌握状态。')}catch(e){setMsg(e.message)}}
 async function submitAttempt(promote=false){if(!attemptDraft?.answer?.trim())return;try{const a=await api(`/practice/${attemptDraft.item.id}/attempts`,{method:'POST',body:JSON.stringify({answer:attemptDraft.answer,is_correct:attemptDraft.correct,feedback:attemptDraft.feedback||''})});if(promote)await api(`/practice/attempts/${a.id}/promote-evidence`,{method:'POST',body:JSON.stringify({note:'用户在学习工作区明确选择保留这次作答作为掌握证据。'})});setAttemptDraft(null);await loadTopic();setMsg(promote?'作答已保存，并由你明确保留为掌握证据；掌握等级仍不会自动改变。':'作答已保存，没有自动改变掌握等级。')}catch(e){setMsg(e.message)}}
 function toggleKb(id){setSelectedKb(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}
 const masteryTasks=useMemo(()=>concepts.map(x=>({id:x.concept.id,title:x.concept.name,detail:x.concept.definition,status:x.mastery?.state==='stable_expression'?'completed':'running',meta:states.find(([v])=>v===(x.mastery?.state||'unfamiliar'))?.[1]})),[concepts]);
 return <div className="stack">
 <section className="pageLead"><div><div className="eyebrow">学习</div><h1>用自己的话理解，用真实练习留下证据。</h1><p className="muted">概念、笔记和练习会分别保存。一次答对不会自动代表掌握，是否保留为证据由你决定。</p></div><StatusChip tone="success">{runtimeCopy.dataStatusLabel}</StatusChip></section>{msg&&<p className="notice">{msg}</p>}
 <WorkspaceBoard pageId="learning" data={workspace.data} loading={workspace.loading} compact title="学习工作台"/>
 <section className="card"><div className="cardHeader"><div><div className="eyebrow">当前范围</div><h2>学习主题</h2></div><select className="compactSelect" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">不限定主题</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></div><FilterTabs value={tab} onChange={setTab} items={[{value:'concepts',label:'概念',count:concepts.length},{value:'notes',label:'笔记',count:notes.length},{value:'practice',label:'练习',count:practice.length},{value:'context',label:'学习上下文',count:bases.length}]}/></section>
 {tab==='concepts'&&<><div className="grid two"><section className="card"><h2>建立一个概念</h2><form className="stack" onSubmit={createConcept}><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="概念名称" required/><textarea value={form.definition} onChange={e=>setForm({...form,definition:e.target.value})} placeholder="先用你自己的话解释它"/><button>保存概念</button></form></section><RecommendationCard eyebrow="掌握方式" title="让掌握状态由证据推动，而不是由 AI 宣布" description="你可以调整当前自评状态，也可以通过深入提问或学习路径收集更多候选证据。" alternatives={[{title:'先记一条笔记',meta:'低能量也有效'},{title:'先做一次练习',meta:'观察自己的解释'}]}/></div><section className="card"><div className="cardHeader"><h2>概念与理解</h2><StatusChip>{concepts.length} 个概念</StatusChip></div><TaskRows tasks={masteryTasks}/>{concepts.map(x=><div className="buiInlineEditor" key={x.concept.id}><div><strong>{x.concept.name}</strong><p>{x.concept.definition}</p></div><select value={x.mastery?.state||'unfamiliar'} onChange={e=>mastery(x.concept.id,e.target.value)}>{states.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><SelectionActions label="针对这个概念" actions={[{label:'生成学习路径',onClick:()=>assist(x.concept.id,'guided-path'),primary:true},{label:'深入提问',onClick:()=>assist(x.concept.id,'deep-question')},{label:'画图理解',onClick:()=>assist(x.concept.id,'visualize')}]} /></div>)}</section></>}
 {tab==='notes'&&<section className="grid two"><div className="card"><h2>写一条学习笔记</h2><form className="stack" onSubmit={addNote}><select value={note.concept_id} onChange={e=>setNote({...note,concept_id:e.target.value})}><option value="">不绑定概念</option>{concepts.map(x=><option key={x.concept.id} value={x.concept.id}>{x.concept.name}</option>)}</select><input value={note.title} onChange={e=>setNote({...note,title:e.target.value})} placeholder="笔记标题" required/><textarea value={note.body_markdown} onChange={e=>setNote({...note,body_markdown:e.target.value})} placeholder="自己的解释、疑问或灵感"/><button>保存笔记</button></form></div><div className="card"><RecordsTable columns={[{key:'title',label:'笔记'},{key:'status',label:'状态'},{key:'body_markdown',label:'内容预览',render:r=><span>{r.body_markdown?.slice(0,90)||'—'}</span>}]} rows={notes.slice(0,20)}/></div></section>}
 {tab==='practice'&&<section className="grid two"><div className="card"><h2>新增一道练习</h2><form className="stack" onSubmit={addPractice}><select value={question.concept_id} onChange={e=>setQuestion({...question,concept_id:e.target.value})}><option value="">不绑定概念</option>{concepts.map(x=><option key={x.concept.id} value={x.concept.id}>{x.concept.name}</option>)}</select><textarea value={question.prompt} onChange={e=>setQuestion({...question,prompt:e.target.value})} placeholder="用什么问题检验理解？" required/><button>加入练习</button></form></div><div className="card"><RecordsTable columns={[{key:'item',label:'问题',render:r=><strong>{r.item.prompt}</strong>},{key:'attempts',label:'作答次数',render:r=>r.attempts.length},{key:'action',label:'回顾',render:r=><button className="tableLink" onClick={()=>setAttemptDraft({item:r.item,answer:'',correct:false,feedback:''})}>回答一次</button>}]} rows={practice.slice(0,20)}/></div></section>}
 {attemptDraft&&<ApprovalCard eyebrow="回顾这次练习" title={attemptDraft.item.prompt} description="先保存真实回答，再决定是否把这次作答保留为掌握证据。二者都不会自动改变掌握等级。" tone="warning" onCancel={()=>setAttemptDraft(null)} actions={<><button className="secondary" onClick={()=>submitAttempt(false)}>只保存作答</button><button onClick={()=>submitAttempt(true)}>保存并保留为证据</button></>}><textarea value={attemptDraft.answer} onChange={e=>setAttemptDraft({...attemptDraft,answer:e.target.value})} placeholder="你的回答" autoFocus/><label className="check"><input type="checkbox" checked={attemptDraft.correct} onChange={e=>setAttemptDraft({...attemptDraft,correct:e.target.checked})}/><span>我愿意把这次回答标记为“答对 / 基本成立”</span></label><textarea value={attemptDraft.feedback} onChange={e=>setAttemptDraft({...attemptDraft,feedback:e.target.value})} placeholder="可选：为什么这样判断？"/></ApprovalCard>}
 {tab==='context'&&<div className="grid two"><section className="card"><h2>可参考的资料库</h2>{bases.map(k=><label className="check" key={k.id}><input type="checkbox" checked={selectedKb.includes(k.id)} onChange={()=>toggleKb(k.id)}/><span>{k.name} · {k.status}</span></label>)}</section><section className="card"><h2>导师角色</h2><InsightCards items={personas.map(p=>({id:p.id,label:p.sync_status==='local'?'本地':p.sync_status,title:p.name,detail:p.description||'学习行为与语气预设'}))}/></section></div>}
 </div>
}
