'use client';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../../lib/api';
import { FilterTabs, PromptBar, RecommendationCard, RecordsTable, StatusChip } from '../../components/BeautifulUI';
export default function CuriosityPage() {
  const [question, setQuestion] = useState(''); const [energy, setEnergy] = useState('normal'); const [items, setItems] = useState([]); const [message, setMessage] = useState(''); const [quick, setQuick] = useState({}); const [filter,setFilter]=useState('all');
  const load = () => api('/questions').then(x => setItems(x.questions)); useEffect(() => { load().catch(() => {}); }, []);
  async function create() {if (!question.trim()) return;await api('/questions', { method: 'POST', body: JSON.stringify({ question, energy_mode: energy, interest_level: 3 }) });setQuestion(''); setMessage('已记录。现在直接离开也完全可以。'); await load();}
  async function action(id, name) {await api(`/questions/${id}/${name}`, { method: 'POST' });if (name === 'close') setQuick(prev => { const next = {...prev}; delete next[id]; return next; });await load();}
  async function quickExplore(id) {const result = await api(`/questions/${id}/quick-explore`, { method: 'POST', body: JSON.stringify({}) });setQuick(prev => ({...prev, [id]: result.exploration}));await load();}
  const filtered=useMemo(()=>filter==='all'?items:items.filter(q=>q.state===filter),[items,filter]);
  return <div className="stack"><section className="pageLead"><div><div className="eyebrow">好奇心</div><h1>先把真正想知道的事接住。</h1><p className="muted">快速看看只是帮你降低启动成本，不等于已经得到证据。任何问题都可以暂停、回来或结束。</p></div><StatusChip tone="success">随时可暂停</StatusChip></section>{message&&<p className="notice">{message}</p>}<section className="card"><div className="cardHeader"><div><h2>记录一个真实问题</h2><p className="muted">按 Enter 提交，Shift + Enter 换行。</p></div></div><PromptBar value={question} onChange={setQuestion} onSubmit={create} placeholder="最近有什么问题、技能或作品让你想多看一眼？" model={({light:'轻量',normal:'适中',deep:'深入'})[energy]} hint="投入强度由你决定" commands={false}/></section><section className="card"><FilterTabs value={filter} onChange={setFilter} items={[{value:'all',label:'全部',count:items.length},{value:'captured',label:'刚记下',count:items.filter(x=>x.state==='captured').length},{value:'paused',label:'已暂停',count:items.filter(x=>x.state==='paused').length},{value:'active_topic',label:'长期主题',count:items.filter(x=>x.state==='active_topic').length},{value:'closed',label:'已结束',count:items.filter(x=>x.state==='closed').length}]}/><RecordsTable columns={[{key:'question',label:'问题',render:q=><strong>{q.question}</strong>},{key:'state',label:'状态',render:q=><StatusChip tone={q.state==='closed'?'neutral':q.state==='active_topic'?'success':'accent'}>{({captured:'刚记下',paused:'已暂停',active_topic:'长期主题',closed:'已结束'})[q.state]||q.state}</StatusChip>},{key:'energy_mode',label:'投入',render:q=>({light:'轻量',normal:'适中',deep:'深入'})[q.energy_mode]||q.energy_mode},{key:'actions',label:'可以做什么',render:q=><div className="buiRowActions"><button className="tableLink" onClick={()=>quickExplore(q.id)}>快速看看</button><button className="tableLink" onClick={()=>action(q.id,'pause')}>暂停</button><button className="tableLink" onClick={()=>action(q.id,'return')}>重新回来</button><button className="tableLink" onClick={()=>action(q.id,'promote')}>转为主题</button><button className="tableLink quiet" onClick={()=>action(q.id,'close')}>结束</button></div>}]} rows={filtered}/></section>{Object.entries(quick).map(([id,x])=><RecommendationCard key={id} eyebrow="快速探索 · 不是证据" title="先得到一个低门槛的方向感" description={x.content} confidence={0.45} alternatives={[{title:'到这里结束',meta:'也完全可以'},{title:'转入研究',meta:'开始核对来源和证据'}]} actions={<StatusChip>{x.provider}</StatusChip>}/>)}</div>;
}
