'use client';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../../lib/api';
import { energyLabel, questionLabel, toUserMessage } from '../../lib/presentation.js';
import { FilterTabs, PromptBar, RecommendationCard, RecordsTable, StatusChip } from '../../components/BeautifulUI';
export default function CuriosityPage() {
  const [question, setQuestion] = useState(''); const [energy, setEnergy] = useState('normal'); const [items, setItems] = useState([]); const [message, setMessage] = useState(''); const [quick, setQuick] = useState({}); const [filter,setFilter]=useState('all'); const [busy,setBusy]=useState(false); const [busyId,setBusyId]=useState('');
  const load = () => api('/questions').then(x => setItems(x.questions)); useEffect(() => { load().catch(() => {}); }, []);
  async function create() {if (busy||!question.trim()) return;setBusy(true);setBusyId('create');try{await api('/questions', { method: 'POST', body: JSON.stringify({ question, energy_mode: energy, interest_level: 3 }) });setQuestion(''); setMessage('已记录。现在直接离开也完全可以。'); await load();}catch(error){setMessage(toUserMessage(error))}finally{setBusy(false);setBusyId('')}}
  async function action(id, name) {if (busy)return;setBusy(true);setBusyId(`${name}:${id}`);try{await api(`/questions/${id}/${name}`, { method: 'POST' });if (name === 'close') setQuick(prev => { const next = {...prev}; delete next[id]; return next; });await load();}catch(error){setMessage(toUserMessage(error))}finally{setBusy(false);setBusyId('')}}
  async function quickExplore(id) {if (busy)return;setBusy(true);setBusyId(`explore:${id}`);try{const result = await api(`/questions/${id}/quick-explore`, { method: 'POST', body: JSON.stringify({}) });setQuick(prev => ({...prev, [id]: result.exploration}));await load();}catch(error){setMessage(toUserMessage(error))}finally{setBusy(false);setBusyId('')}}
  const filtered=useMemo(()=>filter==='all'?items:items.filter(q=>q.state===filter),[items,filter]);
  const actionButtons = q => { const canExplore = !['closed', 'active_topic'].includes(q.state); const canPause = ['captured', 'exploring', 'returned'].includes(q.state); const canReturn = ['paused', 'exploring', 'returned'].includes(q.state); const canPromote = ['exploring', 'returned'].includes(q.state); const canClose = q.state !== 'closed'; return <div className="buiRowActions">{canExplore && <button className="tableLink" onClick={()=>quickExplore(q.id)} disabled={busy}>{busyId===`explore:${q.id}`?'正在查看…':'快速了解'}</button>}{canPause && <button className="tableLink" onClick={()=>action(q.id,'pause')} disabled={busy}>{busyId===`pause:${q.id}`?'正在暂停…':'暂停'}</button>}{canReturn && <button className="tableLink" onClick={()=>action(q.id,'return')} disabled={busy}>{busyId===`return:${q.id}`?'正在恢复…':'继续'}</button>}{canPromote && <button className="tableLink" onClick={()=>action(q.id,'promote')} disabled={busy}>{busyId===`promote:${q.id}`?'正在转换…':'转为主题'}</button>}{canClose && <button className="tableLink quiet" onClick={()=>action(q.id,'close')} disabled={busy}>{busyId===`close:${q.id}`?'正在结束…':'结束'}</button>}</div>; };
  return <div className="stack"><section className="pageLead"><div><div className="eyebrow">好奇心</div><h1>先记下真正想知道的事。</h1><p className="muted">快速了解只用于帮你开始，不代表你已经得到证据。任何问题都可以暂停、继续或结束。</p></div><StatusChip tone="success">随时可暂停</StatusChip></section>{message&&<p className="notice">{message}</p>}<section className="card"><div className="cardHeader"><div><h2>记录一个真实问题</h2><p className="muted">先选这次愿意投入多少，再记录问题。</p></div></div><div className="energyModePicker" role="group" aria-label="好奇心投入模式">{[['light','轻量看看'],['normal','正常推进'],['deep','深入投入']].map(([value,label])=><button type="button" key={value} className={energy===value?'active':''} aria-pressed={energy===value} onClick={()=>setEnergy(value)} disabled={busy}>{label}</button>)}</div><PromptBar className="capturePrompt" value={question} onChange={setQuestion} onSubmit={create} disabled={busy} placeholder="有什么问题、技能或作品值得继续了解？" ariaLabel="记录一个真实问题" leadingIcon="pencil" model={energyLabel(energy)} hint="由你决定投入多少" commands={false} sendLabel={busy?'正在记录…':'记录问题'}/></section><section className="card"><FilterTabs value={filter} onChange={setFilter} items={[{value:'all',label:'全部',count:items.length},{value:'captured',label:'刚记下',count:items.filter(x=>x.state==='captured').length},{value:'paused',label:'已暂停',count:items.filter(x=>x.state==='paused').length},{value:'active_topic',label:'长期主题',count:items.filter(x=>x.state==='active_topic').length},{value:'closed',label:'已结束',count:items.filter(x=>x.state==='closed').length}]}/><RecordsTable columns={[{key:'question',label:'问题',render:q=><strong>{q.question}</strong>},{key:'state',label:'状态',render:q=><StatusChip tone={q.state==='closed'?'neutral':q.state==='active_topic'?'success':'accent'}>{questionLabel(q.state)}</StatusChip>},{key:'energy_mode',label:'投入',render:q=>energyLabel(q.energy_mode)},{key:'actions',label:'操作',render:q=>actionButtons(q)}]} rows={filtered}/></section>{Object.entries(quick).map(([id,x])=><RecommendationCard key={id} eyebrow="快速探索 · 不是证据" title="先获得一个方向" description={x.content} confidence={0.45} alternatives={[{title:'暂时结束',meta:'之后仍可回来'},{title:'转入研究',meta:'开始核对来源和证据'}]} actions={<StatusChip>{x.provider}</StatusChip>}/>)}</div>;
}
