'use client';
import { useEffect, useMemo, useState } from 'react';
import { api, downloadArtifact } from '../../lib/api';
import { ApprovalCard, CodeBlock, RecommendationCard, RecordsTable, SafeSvgPreview, StatusChip } from '../../components/BeautifulUI';
import { WorkspaceBoard, useWorkspaceData } from '../../components/WorkspaceWidgets';

export default function ContentPage() {
  const workspace=useWorkspaceData();
  const [area,setArea]=useState(null), [topics,setTopics]=useState([]), [topic,setTopic]=useState(''), [claims,setClaims]=useState([]), [selected,setSelected]=useState([]);
  const [notes,setNotes]=useState([]), [activities,setActivities]=useState([]), [refs,setRefs]=useState([]);
  const [pack,setPack]=useState(null); const [card,setCard]=useState(null); const [err,setErr]=useState(''); const [approved,setApproved]=useState(false);
  const [cardForm,setCardForm]=useState({layout:'three_points',title:'',points:'',footer:'人工审核后发布'});
  async function loadTopics(){const [x,a]=await Promise.all([api('/topics'),api('/areas/current')]);setArea(a);setTopics(x.topics||[]);if(!topic&&x.topics?.length)setTopic(x.topics[0].id);}
  async function loadGrounding(id=topic){if(!id){setClaims([]);setNotes([]);setActivities([]);return;}const [c,n,a]=await Promise.all([api(`/claims?topic_id=${id}`),api(`/notes?topic_id=${id}`),api(`/activities?topic_id=${id}`)]);setClaims(c.claims||[]);setNotes(n.notes||[]);setActivities(a.activities||[]);setSelected([]);setRefs([]);}
  useEffect(()=>{loadTopics().catch(()=>{});},[]); useEffect(()=>{loadGrounding(topic).catch(()=>{});},[topic]);
  function toggle(id){setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);}
  function toggleRef(ref_type,ref_id){const key=`${ref_type}:${ref_id}`;setRefs(old=>old.some(x=>`${x.ref_type}:${x.ref_id}`===key)?old.filter(x=>`${x.ref_type}:${x.ref_id}`!==key):[...old,{ref_type,ref_id,role:'grounding'}]);}
  async function create(e){e.preventDefault();setErr('');setApproved(false);try{setPack(await api('/content/packs',{method:'POST',body:JSON.stringify({topic_id:topic,claim_ids:selected,grounding_refs:refs,target_audience:'',platform:'xhs',format:'cards'})}));}catch(e){setErr(e.message)}}
  async function approve(){if(!pack?.artifact?.id)return;setErr('');try{await api(`/artifacts/${pack.artifact.id}/approve`,{method:'POST'});setApproved(true);}catch(e){setErr(e.message)}}
  async function exportPack(){if(!pack?.artifact?.id)return;setErr('');try{await downloadArtifact(pack.artifact.id);}catch(e){setErr(e.message)}}
  async function renderCard(e){e.preventDefault();setErr('');try{setCard(await api('/content/cards/render',{method:'POST',body:JSON.stringify({topic_id:topic,layout:cardForm.layout,title:cardForm.title,points:cardForm.points.split('\n').map(x=>x.trim()).filter(Boolean),footer:cardForm.footer})}));}catch(e){setErr(e.message)}}
  const evidenceRequired=Boolean(area?.domain?.content?.evidence_required);
  const claimRows=useMemo(()=>claims.map(item=>({id:item.claim.id,statement:item.current_version?.statement||'—',publishability:item.claim.publishability,verification:item.claim.verification_state,selected:selected.includes(item.claim.id)})),[claims,selected]);
  const groundingRows=useMemo(()=>[
    ...notes.map(x=>({id:x.id,type:'note',title:x.title,detail:x.note_type||'learning note'})),
    ...activities.map(x=>({id:x.id,type:'activity',title:x.objective||x.activity_type,detail:`${x.activity_type} · ${x.status}`})),
  ].map(x=>({...x,selected:refs.some(r=>r.ref_type===x.type&&r.ref_id===x.id)})),[notes,activities,refs]);
  return <div className="stack">
    <section className="pageLead"><div><div className="eyebrow">表达 · {area?.area?.name||'当前兴趣'}</div><h1>把学到的东西，整理成愿意分享的表达。</h1><p className="muted">个人经验与普遍事实会保持不同含义。事实型内容需要经过当前兴趣规则要求的证据和人工确认。</p></div><StatusChip tone={evidenceRequired?'warning':'neutral'}>{evidenceRequired?'需要严格证据':'可灵活选择依据'}</StatusChip></section>{err&&<p className="notice">{err}</p>}
    <WorkspaceBoard pageId="content" data={workspace.data} loading={workspace.loading} compact title="表达工作台"/>
    <section className="card"><div className="cardHeader"><div><h2>选择 Grounding</h2><p className="muted">Claim 是可核验事实理解；Note / Activity 是个人学习或实践记录。二者语义不同，系统不会互相冒充。</p></div><select className="compactSelect" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">选择 Topic</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></div>
      <div className="stack"><div><div className="fieldLabel">Claims {evidenceRequired?'· Psychology factual publishing requires these':''}</div><RecordsTable columns={[{key:'selected',label:'Use',render:r=><input type="checkbox" checked={r.selected} onChange={()=>toggle(r.id)}/>},{key:'statement',label:'Claim'},{key:'publishability',label:'Publishability',render:r=><StatusChip tone={r.publishability==='stable'?'success':'neutral'}>{r.publishability}</StatusChip>},{key:'verification',label:'Verification'}]} rows={claimRows}/></div>
      <div><div className="fieldLabel">Learning / Practice Grounding</div><RecordsTable columns={[{key:'selected',label:'Use',render:r=><input type="checkbox" checked={r.selected} onChange={()=>toggleRef(r.type,r.id)}/>},{key:'type',label:'Type',render:r=><StatusChip>{r.type}</StatusChip>},{key:'title',label:'Record'},{key:'detail',label:'Meaning'}]} rows={groundingRows}/></div></div>
      <div className="row sectionTop"><button onClick={create} disabled={!topic||(!selected.length&&!refs.length)}>生成可审核发布包</button><span className="muted">Claims {selected.length} · Grounding {refs.length}</span></div>
    </section>
    {pack&&<><RecommendationCard eyebrow="Publish Guard" title={pack.pack.ready_for_publication?'规则级检查通过，可以进入人工审核':'存在阻断公开表达的风险'} description={pack.pack.ready_for_publication?'这不是自动批准。请继续检查标题、正文、Grounding 类型、风险说明和媒体提示词。':'后端会拒绝批准与导出，直到当前 Domain Pack 的 Grounding/边界规则被满足。'} confidence={pack.pack.ready_for_publication?0.9:0.99} alternatives={(pack.pack.risk_review||[]).map(x=>({title:x.message,meta:x.severity}))}/><section className="card"><div className="cardHeader"><div><div className="eyebrow">Draft pack</div><h2>{pack.pack.title_candidates?.[0]}</h2></div><StatusChip>{pack.pack.generation?.provider||'deterministic-template'}</StatusChip></div><CodeBlock language="markdown" filename="publish-pack.md" code={pack.pack.body||''}/><div className="grid two sectionTop"><CodeBlock compact language="json" filename="grounding.json" code={JSON.stringify(pack.pack.grounding_refs||[],null,2)}/><CodeBlock compact language="json" filename="media.json" code={JSON.stringify({images:pack.pack.image_prompts||[],video:pack.pack.video_pack||{}},null,2)}/></div></section><ApprovalCard eyebrow="Final human review" title="确认这份内容由你承担" description="批准前请重新检查事实表述、个人经验与普遍结论的边界、引用、标题是否夸大，以及媒体 Prompt 是否引入未经 Grounding 支持的新事实。" tone={pack.pack.ready_for_publication?'warning':'danger'} actions={<><button disabled={!pack.pack.ready_for_publication||approved} onClick={approve}>{approved?'已批准':'我已逐项审核，批准'}</button><button className="secondary" disabled={!approved} onClick={exportPack}>原生导出 ZIP</button></>}>{(pack.pack.risk_review||[]).map((x,i)=><p className="buiReviewLine" key={i}><StatusChip tone={x.severity==='high'?'danger':'warning'}>{x.severity}</StatusChip>{x.message}</p>)}{!pack.pack.risk_review?.length&&<p className="muted">规则检查未发现明显风险；人工审核仍然必须完成。</p>}</ApprovalCard></>}
    <section className="card"><div className="cardHeader"><div><div className="eyebrow">Local visual artifact</div><h2>SVG 信息卡</h2></div><StatusChip>no image API</StatusChip></div><div className="grid two"><form className="stack" onSubmit={renderCard}><select value={cardForm.layout} onChange={e=>setCardForm({...cardForm,layout:e.target.value})}><option value="cover">Cover</option><option value="three_points">Three Points</option><option value="comparison">Comparison</option><option value="evidence">Evidence</option><option value="checklist">Checklist</option><option value="closing">Closing</option></select><input value={cardForm.title} onChange={e=>setCardForm({...cardForm,title:e.target.value})} placeholder="卡片标题" required/><textarea value={cardForm.points} onChange={e=>setCardForm({...cardForm,points:e.target.value})} placeholder={'每行一个要点\n最多 6 条'}/><button>渲染 SVG 卡片</button></form><div>{card?<><SafeSvgPreview svg={card.svg}/><p className="muted">SVG 通过隔离的 image data URI 预览，不注入 Renderer DOM。</p></>:<div className="emptyCanvas">渲染后的信息卡会在这里安全预览。</div>}</div></div></section>
  </div>;
}
