'use client';
import { useEffect, useMemo, useState } from 'react';
import { api, downloadArtifact } from '../../lib/api';
import { ApprovalCard, CodeBlock, RecommendationCard, RecordsTable, SafeSvgPreview, StatusChip } from '../../components/BeautifulUI';
import { WorkspaceBoard, useWorkspaceData } from '../../components/WorkspaceWidgets';
 import { activityLabel, publishabilityLabel, riskReviewLabel, severityLabel, sourceTypeLabel, statusLabel, toUserMessage, verificationLabel } from '../../lib/presentation.js';

export default function ContentPage() {
  const workspace=useWorkspaceData();
  const [area,setArea]=useState(null), [topics,setTopics]=useState([]), [topic,setTopic]=useState(''), [claims,setClaims]=useState([]), [selected,setSelected]=useState([]);
  const [notes,setNotes]=useState([]), [activities,setActivities]=useState([]), [refs,setRefs]=useState([]);
  const [pack,setPack]=useState(null); const [card,setCard]=useState(null); const [err,setErr]=useState(''); const [approved,setApproved]=useState(false); const [busy,setBusy]=useState(false);
  const [cardForm,setCardForm]=useState({layout:'three_points',title:'',points:'',footer:'人工审核后发布'});
  async function loadTopics(){const [x,a]=await Promise.all([api('/topics'),api('/areas/current')]);setArea(a);setTopics(x.topics||[]);if(!topic&&x.topics?.length)setTopic(x.topics[0].id);}
  async function loadGrounding(id=topic){if(!id){setClaims([]);setNotes([]);setActivities([]);return;}const [c,n,a]=await Promise.all([api(`/claims?topic_id=${id}`),api(`/notes?topic_id=${id}`),api(`/activities?topic_id=${id}`)]);setClaims(c.claims||[]);setNotes(n.notes||[]);setActivities(a.activities||[]);setSelected([]);setRefs([]);}
  useEffect(()=>{loadTopics().catch(()=>{});},[]); useEffect(()=>{loadGrounding(topic).catch(()=>{});},[topic]);
  function toggle(id){setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);}
  function toggleRef(ref_type,ref_id){const key=`${ref_type}:${ref_id}`;setRefs(old=>old.some(x=>`${x.ref_type}:${x.ref_id}`===key)?old.filter(x=>`${x.ref_type}:${x.ref_id}`!==key):[...old,{ref_type,ref_id,role:'grounding'}]);}
  async function create(e){e.preventDefault();if(busy)return;setBusy(true);setErr('');setApproved(false);try{setPack(await api('/content/packs',{method:'POST',body:JSON.stringify({topic_id:topic,claim_ids:selected,grounding_refs:refs,target_audience:'',platform:'xhs',format:'cards'})}));}catch(e){setErr(toUserMessage(e))}finally{setBusy(false)}}
  async function approve(){if(!pack?.artifact?.id||busy)return;setBusy(true);setErr('');try{await api(`/artifacts/${pack.artifact.id}/approve`,{method:'POST'});setApproved(true);}catch(e){setErr(toUserMessage(e))}finally{setBusy(false)}}
  async function exportPack(){if(!pack?.artifact?.id||busy)return;setBusy(true);setErr('');try{await downloadArtifact(pack.artifact.id);}catch(e){setErr(toUserMessage(e))}finally{setBusy(false)}}
  async function renderCard(e){e.preventDefault();if(busy)return;setBusy(true);setErr('');try{setCard(await api('/content/cards/render',{method:'POST',body:JSON.stringify({topic_id:topic,layout:cardForm.layout,title:cardForm.title,points:cardForm.points.split('\n').map(x=>x.trim()).filter(Boolean),footer:cardForm.footer})}));}catch(e){setErr(toUserMessage(e))}finally{setBusy(false)}}
  const evidenceRequired=Boolean(area?.domain?.content?.evidence_required);
  const claimRows=useMemo(()=>claims.map(item=>({id:item.claim.id,statement:item.current_version?.statement||'—',publishability:item.claim.publishability,verification:verificationLabel(item.claim.verification_state),selected:selected.includes(item.claim.id)})),[claims,selected]);
  const groundingRows=useMemo(()=>[
    ...notes.map(x=>({id:x.id,type:'note',title:x.title,detail:sourceTypeLabel(x.note_type)})),
    ...activities.map(x=>({id:x.id,type:'activity',title:x.objective||activityLabel(x.activity_type),detail:`${activityLabel(x.activity_type)} · ${statusLabel(x.status)}`})),
  ].map(x=>({...x,selected:refs.some(r=>r.ref_type===x.type&&r.ref_id===x.id)})),[notes,activities,refs]);
  return <div className="stack">
    <section className="pageLead"><div><div className="eyebrow">表达 · {area?.area?.name||'当前兴趣'}</div><h1>把学到的东西，整理成愿意分享的表达。</h1><p className="muted">个人经验与普遍事实会保持不同含义。事实型内容需要满足当前兴趣规则要求的证据和人工确认。</p></div><StatusChip tone={evidenceRequired?'warning':'neutral'}>{evidenceRequired?'需要严格证据':'依据可灵活选择'}</StatusChip></section>{err&&<p className="notice">{err}</p>}
    <WorkspaceBoard pageId="content" data={workspace.data} loading={workspace.loading} compact title="表达工作台"/>
    <section className="card"><div className="cardHeader"><div><h2>选择依据</h2><p className="muted">主张是可核验的事实理解；学习笔记和实践记录属于个人经验。二者语义不同，系统不会互相冒充。</p></div><select aria-label="选择主题" className="compactSelect" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">选择主题</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></div>
      <div className="stack"><div><div className="fieldLabel">事实主张 {evidenceRequired?'· 心理领域的事实表达需要这些依据':''}</div><RecordsTable columns={[{key:'selected',label:'是否使用',render:r=><input type="checkbox" checked={r.selected} onChange={()=>toggle(r.id)}/>},{key:'statement',label:'主张'},{key:'publishability',label:'公开表达范围',render:r=><StatusChip tone={r.publishability==='stable'?'success':'neutral'}>{publishabilityLabel(r.publishability)}</StatusChip>},{key:'verification',label:'核验状态'}]} rows={claimRows}/></div>
      <div><div className="fieldLabel">学习与实践依据</div><RecordsTable columns={[{key:'selected',label:'是否使用',render:r=><input type="checkbox" checked={r.selected} onChange={()=>toggleRef(r.type,r.id)}/>},{key:'type',label:'类型',render:r=><StatusChip>{sourceTypeLabel(r.type)}</StatusChip>},{key:'title',label:'记录'},{key:'detail',label:'含义'}]} rows={groundingRows}/></div></div>
      <div className="row sectionTop"><button onClick={create} disabled={busy||!topic||(!selected.length&&!refs.length)}>{busy?'正在整理…':'生成待审核发布包'}</button><span className="muted">已选主张 {selected.length} · 已选依据 {refs.length}</span></div>
    </section>
    {pack&&<><RecommendationCard eyebrow="发布前检查" title={pack.pack.ready_for_publication?'规则检查通过，可进入人工审核':'存在阻断公开表达的风险'} description={pack.pack.ready_for_publication?'这不是自动批准。请继续检查标题、正文、依据类型、风险说明和媒体提示词。':'后端会拒绝批准和导出，直到当前领域要求的依据与边界规则得到满足。'} confidence={pack.pack.ready_for_publication?0.9:0.99} alternatives={(pack.pack.risk_review||[]).map(x=>({title:riskReviewLabel(x),meta:severityLabel(x.severity)}))}/><section className="card"><div className="cardHeader"><div><div className="eyebrow">待审核内容包</div><h2>{pack.pack.title_candidates?.[0]}</h2></div><StatusChip>{pack.pack.generation?.provider ? '已配置生成通道' : '本地模板'}</StatusChip></div><CodeBlock language="markdown" filename="publish-pack.md" code={pack.pack.body||''}/><div className="grid two sectionTop"><CodeBlock compact language="json" filename="grounding.json" code={JSON.stringify(pack.pack.grounding_refs||[],null,2)}/><CodeBlock compact language="json" filename="media.json" code={JSON.stringify({images:pack.pack.image_prompts||[],video:pack.pack.video_pack||{}},null,2)}/></div></section><ApprovalCard eyebrow="最终人工审核" title="确认由你承担这份内容" description="批准前请重新检查事实表述、个人经验与普遍结论的边界、引用、标题是否夸大，以及媒体提示词是否引入未经依据支持的新事实。" tone={pack.pack.ready_for_publication?'warning':'danger'} actions={<><button disabled={busy||!pack.pack.ready_for_publication||approved} onClick={approve}>{busy?'正在处理…':approved?'已批准':'我已逐项审核，批准'}</button><button className="secondary" disabled={busy||!approved} onClick={exportPack}>导出 ZIP</button></>}>{(pack.pack.risk_review||[]).map((x,i)=><p className="buiReviewLine" key={i}><StatusChip tone={x.severity==='high'?'danger':'warning'}>{severityLabel(x.severity)}</StatusChip>{riskReviewLabel(x)}</p>)}{!pack.pack.risk_review?.length&&<p className="muted">规则检查未发现明显风险；仍需完成人工审核。</p>}</ApprovalCard></>}
    <section className="card"><div className="cardHeader"><div><div className="eyebrow">本地视觉卡片</div><h2>SVG 信息卡</h2></div><StatusChip>当前不使用图像生成接口</StatusChip></div><div className="grid two"><form className="stack" onSubmit={renderCard}><select aria-label="卡片布局" value={cardForm.layout} onChange={e=>setCardForm({...cardForm,layout:e.target.value})}><option value="cover">封面</option><option value="three_points">三个要点</option><option value="comparison">对比</option><option value="evidence">证据</option><option value="checklist">检查清单</option><option value="closing">结尾</option></select><input value={cardForm.title} onChange={e=>setCardForm({...cardForm,title:e.target.value})} placeholder="卡片标题" required/><textarea value={cardForm.points} onChange={e=>setCardForm({...cardForm,points:e.target.value})} placeholder={'每行一个要点\n最多 6 条'}/><button disabled={busy}>{busy?'正在渲染…':'渲染 SVG 卡片'}</button></form><div>{card?<><SafeSvgPreview svg={card.svg}/><p className="muted">SVG 会以隔离方式安全预览，不会直接注入当前页面。</p></>:<div className="emptyCanvas">渲染后的信息卡会在这里安全预览。</div>}</div></div></section>
  </div>;
}
