"use client";

import {
  ArrowClockwise,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ArrowsDownUp,
  BookOpenText,
  Books,
  Briefcase,
  CalendarDots,
  CaretDown,
  CaretRight,
  ChartLineUp,
  Check,
  CheckCircle,
  ChatsCircle,
  Clock,
  Command,
  DotsSixVertical,
  File,
  FileText,
  Flag,
  FolderOpen,
  FolderSimple,
  Gear,
  GraduationCap,
  House,
  Lightbulb,
  LinkSimple,
  ListChecks,
  MagnifyingGlass,
  Moon,
  NotePencil,
  SidebarSimple,
  PaperPlaneTilt,
  PencilSimple,
  Plus,
  Question,
  Quotes,
  Rows,
  SlidersHorizontal,
  Sparkle,
  SquaresFour,
  Stack,
  Sun,
  Target,
  Toolbox,
  TrendUp,
  UserFocus,
  WarningCircle,
  Wrench,
  X,
} from '@phosphor-icons/react';

const ICONS = {
  activity: ChartLineUp,
  approval: CheckCircle,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  book: BookOpenText,
  briefcase: Briefcase,
  calendar: CalendarDots,
  check: Check,
  chevron: CaretRight,
  chevronDown: CaretDown,
  clock: Clock,
  close: X,
  command: Command,
  dashboard: SquaresFour,
  drag: DotsSixVertical,
  file: File,
  filter: SlidersHorizontal,
  flag: Flag,
  folder: FolderSimple,
  growth: TrendUp,
  heatmap: CalendarDots,
  home: House,
  learn: GraduationCap,
  library: Books,
  lightbulb: Lightbulb,
  link: LinkSimple,
  list: ListChecks,
  moon: Moon,
  outputs: FolderOpen,
  panel: SidebarSimple,
  pen: NotePencil,
  pencil: PencilSimple,
  plus: Plus,
  question: Question,
  quote: Quotes,
  refresh: ArrowClockwise,
  reorder: ArrowsDownUp,
  rows: Rows,
  search: MagnifyingGlass,
  send: PaperPlaneTilt,
  settings: Gear,
  source: FileText,
  spark: Sparkle,
  stack: Stack,
  status: CheckCircle,
  sun: Sun,
  target: Target,
  tool: Wrench,
  toolbox: Toolbox,
  tutor: ChatsCircle,
  user: UserFocus,
  warning: WarningCircle,
};

export default function Icon({ name, size = 18, weight = 'regular', ...props }) {
  const Component = ICONS[name] || Sparkle;
  return <Component size={size} weight={weight} aria-hidden="true" {...props}/>;
}
