'use client';
import { useEffect, useMemo, useState } from 'react';
import { api, apiForm } from '../../lib/api';
import { ContextCards, FilterTabs, PixelLoader, PromptBar, RecordsTable, StatusChip, TaskRows, ToolChips } from '../../components/BeautifulUI';
import { WorkspaceBoard, useWorkspaceData } from '../../components/WorkspaceWidgets';
export default function KnowledgePage(){
 const workspace=useWorkspaceData();
 const [bases,setBases]=useState([]),[providers,setProviders]=useState([]),[sources,setSources]=useState([]),[topics,setTopics]=useState([]),[kbId,setKbId]=useState(''),[maps,setMaps]=useState([]),[runs,setRuns]=useState([]),[candidates,setCandidates]=useState([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[tab,setTab]=useState('sources');
 const [kb,setKb]=useState({name:'兴趣资料库',description:'',rag_provider:'native-lexical'}),[upload,setUpload]=useState({file:null,title:'',topic_id:''});
 async function load(){const [b,p,s,t]=await Promise.all([api('/knowledge/bases'),api('/knowledge/providers'),api('/sources'),api('/topics')]);setBases(b.knowledge_bases||[]);setProviders(p.providers||[]);setSources(s.sources||[]);setTopics(t.topics||[]);if(!kbId&&b.knowledge_bases?.length)setKbId(b.knowledge_bases[0].id)} async function detail(id=kbId){if(!id){setMaps([]);setRuns([]);setCandidates([]);return}const [m,r,c]=await Promise.all([api(`/knowledge/bases/${id}/indexes`),api(`/knowledge/bases/${id}/ingestion-runs`),api(`/knowledge/retrieval-candidates?knowledge_base_id=${id}`)]);setMaps(m.indexes||[]);setRuns(r.ingestion_runs||[]);setCandidates(c.candidates||[])}
 useEffect(()=>{load().catch(e=>setMsg(e.message))},[]);useEffect(()=>{detail(kbId).catch(e=>setMsg(e.message))},[kbId]);
 async function create(e){e.preventDefault();try{const x=await api('/knowledge/bases',{method:'POST',body:JSON.stringify(kb)});await load();setKbId(x.id)}catch(e){setMsg(e.message)}} async function uploadFile(e){e.preventDefault();if(!upload.file)return;const fd=new FormData();fd.append('file',upload.file);fd.append('topic_id',upload.topic_id);fd.append('title',upload.title);fd.append('source_type','document');try{await apiForm('/knowledge/sources/upload',fd);await load();setMsg('原文件已归档到本地 Source Library。')}catch(e){setMsg(e.message)}} async function sync(id){setBusy(true);try{const x=await api(`/knowledge/bases/${kbId}/sources/${id}/sync`,{method:'POST'});setMsg(`Ingestion ${x.ingestion_run_id} 已启动。`);await detail()}catch(e){setMsg(e.message)}finally{setBusy(false)}} async function refresh(run){try{const x=await api(`/knowledge/ingestion-runs/${run.id}/refresh`,{method:'POST'});setMsg(`Run ${run.id.slice(0,8)}: ${x.status}${x.task_identity_verified?' · task verified':' · KB-level / unverified task identity'}`);await load();await detail()}catch(e){setMsg(e.message)}} async function rebuild(){setBusy(true);try{const x=await api(`/knowledge/bases/${kbId}/rebuild`,{method:'POST'});setMsg(`单一 multi-file ingestion 已启动：${x.ingestion_run_id}`);await detail()}catch(e){setMsg(e.message)}finally{setBusy(false)}} async function retrieve(){if(!query.trim())return;setBusy(true);try{const x=await api(`/knowledge/bases/${kbId}/retrieve`,{method:'POST',body:JSON.stringify({query,use_evidence_skill:true})});setMsg(`检索完成，保存 ${x.result.provenance_candidates?.length||0} 条 provenance candidate；不是 Evidence。`);await detail()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 const runTasks=useMemo(()=>runs.map(r=>({id:r.id,title:r.operation,detail:`${r.source_ids.length} sources · task ${r.upstream_task_id||'not exposed'}`,status:r.state==='completed'?'completed':r.state==='failed'?'failed':'running',meta:r.task_identity_verified?'identity verified':'identity unverified'})),[runs]);
 return <div className="stack"><section className="pageLead"><div><div className="eyebrow">资料库</div><h1>原始资料留在本机，检索索引随时可以重建。</h1><p className="muted">检索结果只是带来源的候选片段，不会自动变成已经核验的证据。</p></div><StatusChip tone="success">原文件优先</StatusChip></section>{msg&&<p className="notice">{msg}</p>}{busy&&<PixelLoader label="正在整理资料"/>}<WorkspaceBoard pageId="knowledge" data={workspace.data} loading={workspace.loading} compact title="资料工作台"/>
 <div className="grid two"><section className="card"><div className="cardHeader"><h2>知识库</h2><ToolChips tools={providers.map(p=>({name:p.name||p.id,status:p.id===kb.rag_provider?'done':'available'}))}/></div><form className="stack" onSubmit={create}><input value={kb.name} onChange={e=>setKb({...kb,name:e.target.value})}/><select value={kb.rag_provider} onChange={e=>setKb({...kb,rag_provider:e.target.value})}>{providers.filter(p=>p.ingestion_supported!==false).map(p=><option key={p.id} value={p.id}>{p.name||p.id}</option>)}</select><button>保存定义</button></form><select className="sectionTop" value={kbId} onChange={e=>setKbId(e.target.value)}><option value="">选择知识库</option>{bases.map(b=><option key={b.id} value={b.id}>{b.name} · {b.status}</option>)}</select><button className="secondary sectionTop" disabled={!kbId||busy} onClick={rebuild}>从本地所有 Source 单次重建</button></section><section className="card"><h2>上传 Source</h2><form className="stack" onSubmit={uploadFile}><input type="file" onChange={e=>setUpload({...upload,file:e.target.files?.[0]||null})}/><input placeholder="标题" value={upload.title} onChange={e=>setUpload({...upload,title:e.target.value})}/><select value={upload.topic_id} onChange={e=>setUpload({...upload,topic_id:e.target.value})}><option value="">不绑定 Topic</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><button>只存本地</button></form><RecordsTable columns={[{key:'title',label:'Local Source'},{key:'local_file',label:'Action',render:s=><button className="tableLink" disabled={!kbId||busy||!s.local_file} onClick={()=>sync(s.id)}>Link + Sync</button>}]} rows={sources.filter(s=>s.local_file).slice(0,12)}/></section></div>
 <section className="card"><FilterTabs value={tab} onChange={setTab} items={[{value:'sources',label:'Mappings',count:maps.length},{value:'runs',label:'Ingestion runs',count:runs.length},{value:'retrieve',label:'RAG context',count:candidates.length}]}/>{tab==='sources'&&<RecordsTable columns={[{key:'source',label:'Source',render:r=>r.source?.title||'—'},{key:'index',label:'Mapping state',render:r=><StatusChip>{r.index.status}</StatusChip>},{key:'file',label:'Upstream file',render:r=>r.index.upstream_file_name||'—'}]} rows={maps}/>} {tab==='runs'&&<><TaskRows tasks={runTasks}/>{runs.map(r=><div className="buiRunAction" key={r.id}><span>{r.id.slice(0,8)}</span><button className="tableLink" onClick={()=>refresh(r)}>刷新 Run</button></div>)}</>} {tab==='retrieve'&&<><PromptBar value={query} onChange={setQuery} onSubmit={retrieve} disabled={!kbId||busy} placeholder="基于当前资料库检索…" model="RAG + provenance"/><ContextCards items={candidates.slice(0,20).map(c=>({id:c.id,title:c.upstream_file_name||'Unmapped candidate',text:c.excerpt||'无 excerpt',source:c.source_id?`Local Source ${c.source_id}`:'未能映射到本地 Source',location:c.location||'位置未返回'}))} countLabel={`${candidates.length} provenance candidates · not evidence`}/></>}</section>
 </div>
}
