'use client';
import { useEffect, useMemo, useState } from 'react';
import { api, apiForm, pickSourceFile, supportsDocumentPicker, uploadSourceByUri } from '../../lib/api';
import { ContextCards, FilterTabs, PixelLoader, PromptBar, RecordsTable, StatusChip, TaskRows, ToolChips } from '../../components/BeautifulUI';
import { WorkspaceBoard, useWorkspaceData } from '../../components/WorkspaceWidgets';
import { useRuntimeCopy } from '../../components/useRuntimeCopy';
import { statusLabel, toUserMessage } from '../../lib/presentation.js';
export default function KnowledgePage(){
 const workspace=useWorkspaceData();
 const runtimeCopy=useRuntimeCopy();
 const [bases,setBases]=useState([]),[providers,setProviders]=useState([]),[sources,setSources]=useState([]),[topics,setTopics]=useState([]),[kbId,setKbId]=useState(''),[maps,setMaps]=useState([]),[runs,setRuns]=useState([]),[candidates,setCandidates]=useState([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[tab,setTab]=useState('sources');
 const [kb,setKb]=useState({name:'兴趣资料库',description:'',rag_provider:'native-lexical'}),[upload,setUpload]=useState({file:null,uri:null,name:'',mimeType:'',title:'',topic_id:''}),[docPicker,setDocPicker]=useState(false);
 async function load(){const [b,p,s,t]=await Promise.all([api('/knowledge/bases'),api('/knowledge/providers'),api('/sources'),api('/topics')]);setBases(b.knowledge_bases||[]);setProviders(p.providers||[]);setSources(s.sources||[]);setTopics(t.topics||[]);if(!kbId&&b.knowledge_bases?.length)setKbId(b.knowledge_bases[0].id)} async function detail(id=kbId){if(!id){setMaps([]);setRuns([]);setCandidates([]);return}const [m,r,c]=await Promise.all([api(`/knowledge/bases/${id}/indexes`),api(`/knowledge/bases/${id}/ingestion-runs`),api(`/knowledge/retrieval-candidates?knowledge_base_id=${id}`)]);setMaps(m.indexes||[]);setRuns(r.ingestion_runs||[]);setCandidates(c.candidates||[])}
 useEffect(()=>{load().catch(e=>setMsg(toUserMessage(e)))},[]);useEffect(()=>{detail(kbId).catch(e=>setMsg(toUserMessage(e)))},[kbId]);useEffect(()=>{supportsDocumentPicker().then(setDocPicker).catch(()=>setDocPicker(false))},[]);
 async function create(e){e.preventDefault();if(busy)return;setBusy(true);try{const x=await api('/knowledge/bases',{method:'POST',body:JSON.stringify(kb)});await load();setKbId(x.id)}catch(e){setMsg(toUserMessage(e))}finally{setBusy(false)}}
 async function pickFile(){if(busy)return;setBusy(true);try{const picked=await pickSourceFile();if(picked){setUpload({...upload,file:null,uri:picked.uri,name:picked.name||'document',mimeType:picked.mimeType||''});setMsg(`已选择：${picked.name||picked.uri}`)}}catch(e){setMsg(toUserMessage(e))}finally{setBusy(false)}}
 async function uploadFile(e){e.preventDefault();if(busy)return;if(upload.uri){setBusy(true);try{await uploadSourceByUri({path:'/knowledge/sources/upload',uri:upload.uri,fileName:upload.name,fileContentType:upload.mimeType||undefined,fields:{topic_id:upload.topic_id,title:upload.title,source_type:'document'}});await load();setMsg('原文件已归档到本地资料库。')}catch(e){setMsg(toUserMessage(e))}finally{setBusy(false)}return}if(!upload.file)return;const fd=new FormData();fd.append('file',upload.file);fd.append('topic_id',upload.topic_id);fd.append('title',upload.title);fd.append('source_type','document');setBusy(true);try{await apiForm('/knowledge/sources/upload',fd);await load();setMsg('原文件已归档到本地资料库。')}catch(e){setMsg(toUserMessage(e))}finally{setBusy(false)}}
 async function sync(id){if(busy)return;setBusy(true);try{const x=await api(`/knowledge/bases/${kbId}/sources/${id}/sync`,{method:'POST'});setMsg(`资料处理任务已启动：${x.ingestion_run_id}`);await detail()}catch(e){setMsg(toUserMessage(e))}finally{setBusy(false)}}
 async function refresh(run){if(busy)return;setBusy(true);try{const x=await api(`/knowledge/ingestion-runs/${run.id}/refresh`,{method:'POST'});setMsg(`任务 ${run.id.slice(0,8)}：${statusLabel(x.status)}${x.task_identity_verified?' · 任务身份已确认':' · 资料库级任务 · 身份未确认'}`);await load();await detail()}catch(e){setMsg(toUserMessage(e))}finally{setBusy(false)}}
 async function rebuild(){if(busy)return;setBusy(true);try{const x=await api(`/knowledge/bases/${kbId}/rebuild`,{method:'POST'});setMsg(`单次多文件索引已启动：${x.ingestion_run_id}`);await detail()}catch(e){setMsg(toUserMessage(e))}finally{setBusy(false)}}
 async function retrieve(){if(busy||!query.trim())return;setBusy(true);try{const x=await api(`/knowledge/bases/${kbId}/retrieve`,{method:'POST',body:JSON.stringify({query,use_evidence_skill:true})});setMsg(`检索完成，保存 ${x.result.provenance_candidates?.length||0} 条带来源候选片段；尚不能视为证据。`);await detail()}catch(e){setMsg(toUserMessage(e))}finally{setBusy(false)}}
 const runTasks=useMemo(()=>runs.map(r=>({id:r.id,title:'资料处理任务',detail:`${r.source_ids.length} 个来源 · 任务 ${r.upstream_task_id||'未提供'}`,status:r.state==='completed'?'completed':r.state==='failed'?'failed':'running',metaLabel:r.task_identity_verified?'身份已确认':'身份未确认'})),[runs]);
 return <div className="stack"><section className="pageLead"><div><div className="eyebrow">资料库</div><h1>{runtimeCopy.knowledgeHeadline}</h1><p className="muted">检索结果只是带来源的候选片段，不会自动变成已经核验的证据。</p></div><StatusChip tone="success">原文件优先</StatusChip></section>{msg&&<p className="notice">{msg}</p>}{busy&&<PixelLoader label="正在整理资料"/>}<WorkspaceBoard pageId="knowledge" data={workspace.data} loading={workspace.loading} compact title="资料工作台"/>
 <div className="grid two"><section className="card"><div className="cardHeader"><h2>知识库</h2><ToolChips tools={providers.map(p=>({name:p.name||p.id,status:p.id===kb.rag_provider?'done':'available'}))}/></div><form className="stack" onSubmit={create}><input aria-label="知识库名称" value={kb.name} onChange={e=>setKb({...kb,name:e.target.value})}/><select aria-label="RAG 提供器" value={kb.rag_provider} onChange={e=>setKb({...kb,rag_provider:e.target.value})}>{providers.filter(p=>p.ingestion_supported!==false).map(p=><option key={p.id} value={p.id}>{p.name||p.id}</option>)}</select><button disabled={busy}>{busy?'正在保存…':'保存定义'}</button></form><select aria-label="选择知识库" className="sectionTop" value={kbId} onChange={e=>setKbId(e.target.value)} disabled={busy}><option value="">选择知识库</option>{bases.map(b=><option key={b.id} value={b.id}>{b.name} · {statusLabel(b.status)}</option>)}</select><button className="secondary sectionTop" disabled={!kbId||busy} onClick={rebuild}>{busy?'正在重建…':'从本地资料进行单次重建'}</button></section><section className="card"><h2>上传资料</h2><form className="stack" onSubmit={uploadFile}>{docPicker?<button type="button" className="secondary" onClick={pickFile} disabled={busy}>{upload.name?`已选择：${upload.name}`:'选择文件（系统文档选择器）'}</button>:<input type="file" aria-label="选择上传文件" onChange={e=>setUpload({...upload,file:e.target.files?.[0]||null})} disabled={busy}/>}<input placeholder="标题" value={upload.title} onChange={e=>setUpload({...upload,title:e.target.value})} disabled={busy}/><select aria-label="绑定主题" value={upload.topic_id} onChange={e=>setUpload({...upload,topic_id:e.target.value})} disabled={busy}><option value="">不绑定主题</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><button disabled={busy}>{busy?'正在保存…':'只存本地'}</button></form><RecordsTable columns={[{key:'title',label:'本地资料'},{key:'local_file',label:'操作',render:s=><button className="tableLink" disabled={!kbId||busy||!s.local_file} onClick={()=>sync(s.id)}>{busy?'正在同步…':'关联并同步'}</button>}]} rows={sources.filter(s=>s.local_file).slice(0,12)}/></section></div>
 <section className="card"><FilterTabs value={tab} onChange={setTab} items={[{value:'sources',label:'资料映射',count:maps.length},{value:'runs',label:'索引任务',count:runs.length},{value:'retrieve',label:'RAG 检索上下文',count:candidates.length}]}/>{tab==='sources'&&<RecordsTable columns={[{key:'source',label:'资料',render:r=>r.source?.title||'—'},{key:'index',label:'映射状态',render:r=><StatusChip>{statusLabel(r.index.status)}</StatusChip>},{key:'file',label:'上游文件',render:r=>r.index.upstream_file_name||'—'}]} rows={maps}/>} {tab==='runs'&&<><TaskRows tasks={runTasks}/>{runs.map(r=><div className="buiRunAction" key={r.id}><span>{r.id.slice(0,8)}</span><button className="tableLink" onClick={()=>refresh(r)}>刷新任务</button></div>)}</>} {tab==='retrieve'&&<><PromptBar value={query} onChange={setQuery} onSubmit={retrieve} disabled={!kbId||busy} placeholder="基于当前资料库检索…" model="RAG 检索"/><ContextCards items={candidates.slice(0,20).map(c=>({id:c.id,title:c.upstream_file_name||'尚未映射的候选片段',text:c.excerpt||'没有摘要',source:c.source_id?`本地资料 ${c.source_id}`:'未能映射到本地资料',location:c.location||'位置未返回'}))} countLabel={`${candidates.length} 带来源候选片段 · 尚不能视为证据`}/></>}</section>
 </div>
}
