'use client';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../../lib/api';
import { ApprovalCard, FilterTabs, InsightCards, RecordsTable, StatusChip } from '../../components/BeautifulUI';
import { statusLabel, toUserMessage } from '../../lib/presentation.js';
const directions = ['内容表达','教学/分享','作品/项目','进一步学习或职业探索'];
export default function CareerPage(){
  const [rows,setRows]=useState([]); const [summary,setSummary]=useState(null); const [msg,setMsg]=useState(''); const [filter,setFilter]=useState('all'); const [finishDraft,setFinishDraft]=useState(null);
  const [form,setForm]=useState({direction:directions[0],hypothesis:'',experiment:'',interest_before:3,competence_boundary:'learning_only'}); const [busy,setBusy]=useState(false);
  async function load(){const [x,s]=await Promise.all([api('/career/experiments'),api('/career/summary')]);setRows(x.experiments||[]);setSummary(s);}
  useEffect(()=>{load().catch(e=>setMsg(toUserMessage(e)));},[]);
  async function create(e){e.preventDefault();if(busy)return;setBusy(true);try{await api('/career/experiments',{method:'POST',body:JSON.stringify({...form,interest_before:Number(form.interest_before)})});setForm({...form,hypothesis:'',experiment:''});setMsg('已记录职业实验。这里不要求现在就决定职业方向。');await load();}catch(e){setMsg(toUserMessage(e))}finally{setBusy(false)}}
  async function finish(){if(busy||!finishDraft)return;setBusy(true);try{await api(`/career/experiments/${finishDraft.id}`,{method:'PUT',body:JSON.stringify({evidence:finishDraft.evidence,interest_after:Number(finishDraft.interest_after),status:'completed',reflection:finishDraft.reflection})});setFinishDraft(null);setMsg('实验已完成并记录真实证据。');await load();}catch(e){setMsg(toUserMessage(e))}finally{setBusy(false)}}
  const filtered=useMemo(()=>filter==='all'?rows:rows.filter(r=>r.status===filter),[rows,filter]);
  const completed=rows.filter(r=>r.status==='completed'); const avgBefore=completed.length?completed.reduce((a,r)=>a+Number(r.interest_before||0),0)/completed.length:null; const avgAfter=completed.length?completed.reduce((a,r)=>a+Number(r.interest_after||0),0)/completed.length:null;
  return <div className="stack"><section className="pageLead"><div><div className="eyebrow">职业实验</div><h1>先做一个小实验，再决定要不要走得更远。</h1><p className="muted">用低风险、可逆的行动验证想象。这里只记录体验、能力边界和兴趣变化，不替你做职业决定。</p></div><StatusChip tone="neutral">没有职业 KPI</StatusChip></section>{msg&&<p className="notice">{msg}</p>}
    <InsightCards items={[{label:'已完成实验',title:String(completed.length),detail:'只有做完的真实实验才进入长期信号。'},{label:'实验前兴趣',title:avgBefore==null?'—':avgBefore.toFixed(1),detail:'完成实验的平均起始兴趣'},{label:'实验后兴趣',title:avgAfter==null?'—':avgAfter.toFixed(1),detail:'完成实验后的平均兴趣',tone:avgAfter!=null&&avgBefore!=null&&avgAfter>avgBefore?'positive':''},{label:'当前实验信号',title:summary?.signal?.direction||summary?.most_promising_direction||'仍在探索',detail:`${summary?.signal?.basis||'还没有完成实验。'} 置信度：${summary?.signal?.confidence||'low'}`,tone:summary?.signal?.direction?'accent':'neutral'}]}/>
    {summary?.signal?.ties?.length>1&&<p className="notice">当前有并列方向：{summary.signal.ties.join('、')}。样本仍少，系统不会替你做职业决定。</p>}
    <div className="grid two"><section className="card"><h2>设计一次小实验</h2><form className="stack" onSubmit={create}><select aria-label="实验方向" value={form.direction} onChange={e=>setForm({...form,direction:e.target.value})}>{directions.map(x=><option key={x}>{x}</option>)}</select><input aria-label="实验假设" value={form.hypothesis} onChange={e=>setForm({...form,hypothesis:e.target.value})} placeholder="假设：我可能喜欢/不喜欢什么？"/><textarea aria-label="实验计划" value={form.experiment} onChange={e=>setForm({...form,experiment:e.target.value})} placeholder="具体实验：例如连续做 3 篇证据型心理科普，而不是直接决定转行" required/><label>开始前兴趣 1–5<input aria-label="实验前兴趣" type="number" min="1" max="5" value={form.interest_before} onChange={e=>setForm({...form,interest_before:e.target.value})}/></label><select aria-label="能力边界" value={form.competence_boundary} onChange={e=>setForm({...form,competence_boundary:e.target.value})}><option value="learning_only">仅学习</option><option value="cautious_expression">谨慎公开表达</option><option value="inside_current_competence">当前能力范围内</option><option value="outside_scope">超出当前能力边界</option></select><button disabled={busy}>{busy?'正在记录…':'记录实验'}</button></form></section><section className="card"><div className="cardHeader"><h2>实验记录</h2><FilterTabs value={filter} onChange={setFilter} items={[{value:'all',label:'全部',count:rows.length},{value:'active',label:'进行中',count:rows.filter(r=>r.status==='active').length},{value:'completed',label:'已完成',count:completed.length}]}/></div><RecordsTable columns={[{key:'direction',label:'方向'},{key:'experiment',label:'实验',render:r=><span>{r.experiment.slice(0,90)}</span>},{key:'interest_before',label:'兴趣变化',render:r=><span>{r.interest_before}{r.interest_after?` → ${r.interest_after}`:''}</span>},{key:'status',label:'状态',render:r=>r.status==='completed'?<StatusChip tone="success">已完成</StatusChip>:<button className="tableLink" onClick={()=>setFinishDraft({...r,evidence:r.evidence||'',interest_after:r.interest_after||r.interest_before,reflection:r.reflection||''})} disabled={busy}>记录结果</button>}]} rows={filtered}/></section></div>
    {finishDraft&&<ApprovalCard eyebrow="实验回顾" title={`完成：${finishDraft.direction}`} description={finishDraft.experiment} tone="warning" onCancel={()=>setFinishDraft(null)} actions={<button onClick={finish} disabled={busy||!finishDraft.evidence?.trim()||Number(finishDraft.interest_after)<1||Number(finishDraft.interest_after)>5}>{busy?'正在保存…':'完成并保存'}</button>}><label>真实发生了什么？<textarea value={finishDraft.evidence} onChange={e=>setFinishDraft({...finishDraft,evidence:e.target.value})} placeholder="只写事实证据"/></label><label>做完后的兴趣 1–5<input type="number" min="1" max="5" value={finishDraft.interest_after} onChange={e=>setFinishDraft({...finishDraft,interest_after:e.target.value})}/></label><label>这次实验让你多知道了什么？<textarea value={finishDraft.reflection} onChange={e=>setFinishDraft({...finishDraft,reflection:e.target.value})}/></label></ApprovalCard>}
  </div>
}
